apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend-app
spec:
  selector:
    app: cineverse
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: NodePort